### ISSUE TITLE
Childrens' `GridCell` is ignored

### ISSUE THREAD

**Issue by oli-obk** [aevyrie/big_space#11]
When children of entities have their own `GridCell`, that `GridCell` is ignored entirely (and silently). I think the behaviour should be that the children's `GridCell` is used as a relative offset to the parent.

Alternatively the traversal should emit a warning about the ignored `GridCell`.

What do you think should happen here? I'd be happy to provide the impl

**Comment by aevyrie** [comment]
Nested grids are not supported, though I can see how it could be useful. I'd be interested in supporting this if you implement it.

**Comment by aevyrie** [comment]
This is supported with the addition of `ReferenceFrame`s. These can be nested, and take some extra care to maximize precision.
