### ISSUE TITLE
2+ cameras and render passes / minimap / split screen

### ISSUE THREAD

**Issue by johnny-smitherson** [aevyrie/big_space#17]
Has this been attempted to be used with 2 cameras with different render passes?

Here are some use cases: [bevy split screen example](https://bevyengine.org/examples/3D%20Rendering/split-screen/) and [trackball + minimap](https://qu1x.dev/bevy_trackball/constellation_clamp.html).

Adding 2 objects with the `FloatingOrigin` component triggers panic.

I have not looked too closely at what this would all entail, but I do see 

https://github.com/aevyrie/big_space/blob/2eb87f948d362b8d18ab77ac77bb7b7441482ee4/src/reference_frame/local_origin.rs#L443

This "local floating origin" value that needs to be updated on all the reference frames would need to be computed for each of the cameras/floating origins we want to render from.

And I guess I'd go down the rabbit hole from there, using the correct instance of the data when the correct camera is rendering, right?

Also, bevy seems to only give us `32 RenderLayers` for control of what actually shows up on the cameras - would we need to put the different "local floating origin" recomputations on different layers, or could this be done by changing the data on the fly when doing each camera's render pass?

Finally, is such a feature desired in the lib?

**Comment by aevyrie** [comment]
There is nothing stopping you from using multiple cameras with a single floating origin. The only thing that matters is the distance of each camera from the floating origin. If you have 2 player split screen, you might place the floating origin at the center point between the two players, and prevent them from moving more than a kilometer apart.

The only way to support multiple floating origins would be if each floating origin was operating on an entirely unique set of objects - they could not overlap. So yes, you could use renderlayers for this, but only in cases where an object is on a *single* layer - it's possible for objects to be on many layers. This would require you to effectively have two copies of everything in your world. 

For the case of the minimap or similar, you can simply add the `IgnoreFloatingOrigin` component, and work with those objects as if they were in a normal bevy transform system.

**Comment by johnny-smitherson** [comment]
Thanks for the clarification, I understand things better now.

> you might place the floating origin at the center point between the two players, and prevent them from moving more than a kilometer apart

Yep, tried it and it works great as long as all the cameras are around the same grid cells as you said. Still, I would like to try and work around this limitation. My use case would also be a "spectator mode" where you watch 4-8 players that are spread out further than just a few cells.

>  This would require you to effectively have two copies of everything in your world.

Actually, since the cameras would be so far apart, it makes sense to have a different distance culling and level of detail for each object vs. each camera - so object duplication and one-hot render layers absolutely make sense here.

> The only way to support multiple floating origins would be if each floating origin was operating on an entirely unique set of objects - they could not overlap.

Ah, makes sense, `GlobalTransform` cannot have two values for the same object, you have to pick one or the other. I wonder if I can override the GlobalTransform in the camera's render pipeline extract stage, to get around the "no overlap" limitation - will play with that later, through I think it's low priority considering the "different level of detail" issue.

---

> I wouldn't want to merge it if it greatly increased complexity 

I went ahead and added a `const L: u8=0` generic to everything, to see how that would look like. The plugins, the grid cells, the reference frames, the floating origin, the ignore marker, everything.

Because of the default value of the generic, most of the examples/tests/demo code does not change. Still, there are some structs that were not generic, and now are; and Rust doesn't want to infer the default value of `L` if there's no `P` there too (or I don't know how to do it).

Here are the only structs that require adding explicit `::<0>` to keep current functionality:

- `FloatingOrigin` --> `FloatingOrigin::<0>` (wasn't generic before)
- `IgnoreFloatingOrigin` --> `IgnoreFloatingOrigin::<0>` (wasn't generic before)
- `GridTransformReadOnly<i128>` --> `GridTransformReadOnly<i128, 0>`  (was generic, but the bevy? macro that generates the struct doesn't preserve the default value for L from the original - need upstream fix)

I think we could add the `P` generic parameter to the floating point origin and ignore marker. This would also guard better against accidentally using different precisions


Here is the draft PR to see what it'd look like.

What do you think?

**Comment by johnny-smitherson** [comment]
>  you could have a World for each player

I can have more than 1 World?? Yeah that sounds much better

https://github.com/bevyengine/bevy/discussions/7893

https://github.com/bevyengine/rfcs/pull/16

**Comment by johnny-smitherson** [comment]
Actually, since you were talking about many-World, I guess I will try and spawn a bunch of threads and run separate "App" instances on each.

If that doesn't work out, I can always execute many instances of the game exe with different parameters. It'll be a bunch of OS windows instead of bevy UI TargetCamera, but it'll do until they add some kind of support for multi-World

Thanks for the conversation, very useful, much appreciated

**Comment by aevyrie** [comment]
You can definitely have multiple worlds right now - bevy's pipelined renderer runs in another world, and data is extracted from the simulation world into the render world at the sync point. It's as simple as sticking a `World` inside a resource. The idea is that you would define a simulation in each world, run the schedule one frame, then extract the renderable stuff out into the single render world. The main world would be nothing more than this glue, as well as a place to store all the independent worlds.

**Comment by johnny-smitherson** [comment]
ok i will try and submit example file with a demo and a bunch of cameras, for posterity

**Comment by aevyrie** [comment]
You don't necessarily need multiple worlds - I think you were right on in #19. You could add as many reference frames at the root of the hierarchy, and treat them independently. You will just need to be careful to ensure that everything in that subtree has the correct renderlayer component.
