### ISSUE TITLE
Making `FloatingOriginSettings::new` public?

### ISSUE THREAD

**Issue by tpolakovic** [aevyrie/big_space#2]
The constructor for the settings is not pub, which makes it impossible to make a custom plugin with systems running in a different schedule. If it were to be made public, it will be possible to essentially copy-paste the plugin code with some minor tweaks to run the systems in different schedules (e.g. the fixed time step schedule).

**Comment by aevyrie** [comment]
This has been resolved. It was made private to prevent users accessing the resource and mutating the settings, as this is not valid.
