### ISSUE TITLE
Avoid Spawning a New Big Space Every Time a Component Changes 

### ISSUE THREAD

**Issue by eliasstepanik** [aevyrie/big_space#32]
Hello,

I'm currently working with big_space in a Bevy 0.14 project, and I've encountered an issue where I seem to be spawning a new big space every time I change a component. I would like to understand how to avoid this behavior and ensure that the big space is only spawned once.

Here's a snippet of my code:

```
commands.spawn_big_space(ReferenceFrame::<i128>::default(), |root| {
    let mesh_handle = meshes.add(Sphere::new(0.5).mesh().ico(32).unwrap());
    let matl_handle = materials.add(StandardMaterial {
        base_color: Color::Srgba(palettes::basic::BLUE),
        perceptual_roughness: 0.8,
        reflectance: 1.0,
        ..default()
    });

    let mut translation = Vec3::ZERO;
    for i in -16..=27 {
        let scale = i as f32;
        translation.x += i as f32 + (scale / 2.0);

        root.spawn_spatial(PbrBundle {
            mesh: mesh_handle.clone(),
            material: matl_handle.clone(),
            transform: Transform::from_scale(Vec3::splat(scale)).with_translation(translation),
            ..default()
        });
    }
});
```
I noticed that each time I change a component and run the code, it seems to spawn a new big space. Is there a way to prevent this and reuse the existing big space? How does the spawn_big_space function handle multiple invocations, and what is the best practice for managing big spaces when components change?

Like for example with Ressources.

I appreciate any guidance or suggestions on how to properly use big_space in this context.

Thank you!

Additional Information:

Bevy Version: 0.14
big_space Version: 0.7.0
Operating System: Windows

**Comment by aevyrie** [comment]
I might be missing some context here. `commands.spawn_big_space` is always going to spawn a new big space.

> I noticed that each time I change a component and run the code

What do you mean when you say you change a component? If you are calling the spawn command, you will be spawning a new entity, not modifying an existing one.
