### ISSUE TITLE
Add `#[reflect(Component)]` on `ReferenceFrame`

### ISSUE THREAD

**Issue by SolarLiner** [aevyrie/big_space#33]
I have a custom scene format for describing solar systems, and would like to use the asset processor features of Bevy to convert that format to `DynamicScene`s. However this does not work as the nested reference frames are not serialized; `big_space` then complains about the hierarchy once the serialized scene is loaded in the main world.

To solve this issue, `ReferenceFrame` needs to have `reflect(Component)` added to it, as is already the case with `GridCell`.

**Comment by aevyrie** [comment]
Fixed in 750a9a7
