### ISSUE TITLE
Odd camera behavior

### ISSUE THREAD

**Issue by Lemonzyy** [aevyrie/big_space#4]
I noticed something strange when I tried out the camera of your crate. The camera seems to roll without pressing the corresponding keys, but only by moving the mouse cursor.

https://github.com/aevyrie/big_space/assets/47032639/dff964fc-2e41-41b3-8cb1-64b19eb8e0a3

As you can see in the video (example `demo`), when I move the camera using the mouse, the spheres that were previously aligned horizontally become aligned vertically, proving that the camera is rolling.

**Comment by aevyrie** [comment]
Yup, this is because the camera just applies rotation relative to the current transform. As you move in an arc, you are applying a rotation. This was done to avoid gimbal lock and the need to have an "up" direction.
