### ISSUE TITLE
Use with 2d ?

### ISSUE THREAD

**Issue by Wicpar** [aevyrie/big_space#6]
Hi, I am trying to use the plugin for 2d, however the 2d camera doesn't render beyond the first grid it seems. It also seems wasteful to use the 3d grids for 2d.

how would one use the plugin with 2d ? does the camera need to be custo; to take in account the grid cells ?
I also need world to screenspace functions, i suppose that also needs special treatment.

**Comment by Wicpar** [comment]
I managed to do it, it works great with the GlobalTransforms, then just use the normal camera to screenspace, thanks for the plugin !

**Comment by aevyrie** [comment]
To add some more detail, the plugin doesn't care about the camera at all. It simple updates Transforms and GlobalTransforms based on where the floating origin is relative to each entity's GridCell.
